---
title: "First Knit"
author: "Claryssa Jimenez"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended and graduated from Palmdale High School. I would I say I was better at math, there for I prefer it over English. I always did best in my math and science classes. English and history were too much reading (sorry!).
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
I have my trusty Apple Macbook that my dad bought for me in high school during the beginning of COVID. I would probably rate myself a good 9 on the scale.  After not being able to keep up in class with this knitting stuff, I would say the score has maybe dropped down to a cool 7. I live in the far west side of Lancaster so the connection is pretty decent but not always the best. 

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
Of course my family has their weird funny names for me, but I just like my name as it is. If I did have a name, I'd like to go buy the name my cousins call me by, which is Claire.  
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
I have always known and had a passion for having a career in the medical field. Psychology is so far pretty interesting right now so that might be one that I have a great interest in. I am currently a medical assistant but I want to explore into a different side of the medical field which would be Radiology! I am hoping to be a certified radiology technologist in 2 years! 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




